name: Flutter Windows CI

on:
  push:
    branches: [main]
    tags:
      - 'release'

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
    - name: Get dependencies
      run: flutter pub get
    - name: Enable Windows build
      run: flutter config --enable-windows-desktop
    - name: Build Windows executable
      run: flutter build windows --release
    - name: Upload windows binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.FLUTTER_ROOT }}\build\windows\x64\runner\Release\padel_rating.zip
        overwrite: true
        body: "This is my release text"          
